# Generated by Django 4.0.6 on 2022-07-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='От кого')),
                ('hello', models.TextField(verbose_name='Ваши приветы')),
            ],
        ),
    ]
