# Generated by Django 4.0.6 on 2022-07-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hello',
            options={'verbose_name': 'Привет', 'verbose_name_plural': 'Приветы'},
        ),
        migrations.RenameField(
            model_name='hello',
            old_name='title',
            new_name='froms',
        ),
    ]
